### PR TITLE
Add Call Congress tool

### PR DESCRIPTION
**Pull request by mikemorris**
This PR adds a page at `/call` that's a duplicate of the home page, but with the call tool instead of the petition signup. I think it may be possible to instead rework the home page to replace the petition signup with the call tool if we pass a query string like `?call_tool=1`, but I guess we should focus on just getting something usable pushed live first.

### CODE REVIEW

**Comment by mikemorris** [comment]
Current call tool design looks like this

screen shot 2017-05-03 at 11 31 58 pm

@katro16 @holmesworcester We probably need updated copy and design for a modal similar to https://www.battleforthenet.com/?sharing_modal=1 that would appear when the user clicks the `Call Congress` button

**Comment by mikemorris** [comment]
Call tool content changes to this after clicking the button:

screen shot 2017-05-04 at 10 32 38 am

**Comment by mikemorris** [comment]
Fixed formatting of intro copy and updated headline. Removed the "Thank you for submitting a comment" sentence as it isn't really applicable when this is a landing page instead of an after-action ask.

screen shot 2017-05-04 at 10 46 13 am

**Comment by holmesworcester** [comment]
the script is way too long. we'll need to revine

**Pull request merged**
